trigger:
- main

pool: Default

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: echo 'Downloading dependencies...'
      displayName: 'Download Dependencies'

    - script: echo 'Compiling source code...'
      displayName: 'Compile Source Code'

    - script: echo 'Packaging application...'
      displayName: 'Package Application'

- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: TestJob
    displayName: 'Test Job'
    steps:
    - script: echo 'Running unit tests...'
      displayName: 'Run Unit Tests'

    - script: echo 'Running integration tests...'
      displayName: 'Run Integration Tests'

    - script: echo 'Generating test coverage report...'
      displayName: 'Generate Test Coverage Report'

- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          az login
      displayName: 'Login Azure'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          ids=$(az webapp list --query '[0].id' -o tsv)
          repo_url=https://github.com/Vedanttrivedi/HelloPy
          az webapp deployment source config --branch main --manual-integration --repo-url $repo_url --ids $ids
          az webapp deployment source sync --ids $ids
      displayName: 'Push Azure'
